### ISSUE TITLE
pytest-ibutsu is missing some dependencies

### ISSUE THREAD

**Issue by rsnyman** [ibutsu/pytest-ibutsu#59]
It seems that pytest-ibutsu is missing some dependencies, specifically 'attrs'

**Comment by quarckster** [comment]
`attrs` is specified in dependencies https://github.com/ibutsu/pytest-ibutsu/blob/master/pyproject.toml#L17, and tests pass

**Comment by rsnyman** [comment]
Weird, I installed it on a clean env and it didn't seem to have it. Maybe I had an older version somehow.
