### ISSUE TITLE
Run is no longer updated at the end of the test run

### ISSUE THREAD

**Issue by rsnyman** [ibutsu/pytest-ibutsu#61]
The run object in Ibutsu is no longer updated at the end of the session, resulting in the backend not running the `update_run` task which re-calculates the summary of the run.

**Comment by rsnyman** [comment]
@quarckster this probably happened during your refactor. There is no way for the server to ever know that the test run is complete, hence why the plugin used to update the run at the end of the session.

**Comment by quarckster** [comment]
> There is no way for the server to ever know that the test run is complete, hence why the plugin used to update the run at the end of the session.

Aha, thanks for the tip. I didn't know that the server requires an update call.

**Comment by rsnyman** [comment]
Yes, unfortunately it does. I haven't found an easy way around the issue yet :-(
